//! A plugin handing over a parse table from a Tree-sitter older than this build speaks.
//!
//! Hand-written rather than built by [`groove_grammar_abi::groove_grammar_plugin`], and for a
//! different reason from the other hand-written fixtures here: the macro builds
//! [`crate::groove_grammar_language`] out of a real grammar crate's `LanguageFn`, so every table
//! it hands over is one the Tree-sitter CLI generated at a version this build supports. A table
//! that is a table only in shape is the one thing the macro cannot say.
//!
//! What it pins: **the grammar's own Tree-sitter ABI is checked before anything is built from
//! it.** Without that check, a grammar generated by a CLI this runtime cannot speak goes on to
//! `TagsConfiguration`, which reads the parse table proper.
//!
//! # Why handing over a table that is not one is sound here
//!
//! Between the loader taking this pointer and refusing it, exactly one field is read. Against
//! tree-sitter 0.26.13, read out of the vendored source:
//!
//! - `Language::new` is `Self(unsafe { builder.into_raw()().cast() })` -- it calls the function
//!   and keeps the pointer, and dereferences nothing.
//! - `Language::abi_version` is `ts_language_abi_version`, whose whole body is
//!   `return self->abi_version;`, and `abi_version` is the **first** field of
//!   `struct TSLanguage`.
//! - Dropping the `Language` on the refusal calls `ts_language_delete`, which is
//!   `if (self && ts_language_is_wasm(self))`. Without the `wasm` feature -- which nothing in
//!   this workspace turns on -- `ts_language_is_wasm` is a stub that ignores `self` and returns
//!   false. The `wasm` build of it reads `self->lex_fn`, which is why [`crate::ForgedLanguage`]
//!   carries
//!   room for the rest of the struct rather than stopping after the one field read today.
//!
//! Its pair is `future_tree_sitter.rs`, the same fixture with its version on the other side of
//! the range, so that neither half of the loader's `found < min || found > max` can be deleted
//! without a test going red.

use core::ffi::c_char;

/// A parse table in shape only: the one field Tree-sitter reads before groove refuses it.
///
/// The tail is sized in words rather than bytes because `struct TSLanguage` is mostly pointers,
/// so a word count stays a comfortable overestimate on a 32-bit target as well as a 64-bit one,
/// and the alignment falls out of `usize` rather than needing a `repr(align)` of its own.
#[repr(C)]
struct ForgedLanguage {
    abi_version: u32,
    rest: [usize; 64],
}

/// The point of the fixture: a version below anything this runtime will accept.
///
/// `1` rather than something nearer the boundary because `MIN_COMPATIBLE_LANGUAGE_VERSION` only
/// ever rises -- Tree-sitter drops support for old grammars, it does not regain it. Should that
/// stop being true, this fixture is *accepted* here rather than quietly passing: it declares an
/// extension the loader is not looking for (see [`groove_grammar_extensions`]), so it is refused
/// a few checks later with a different sentence and its test fails saying so.
static FORGED: ForgedLanguage = ForgedLanguage {
    abi_version: 1,
    rest: [0; 64],
};

#[unsafe(no_mangle)]
pub extern "C" fn groove_grammar_abi_version() -> u32 {
    groove_grammar_abi::ABI_VERSION
}

/// Hands over [`FORGED`]: a live, correctly aligned address that is not a grammar.
#[unsafe(no_mangle)]
pub extern "C" fn groove_grammar_language() -> *const () {
    core::ptr::from_ref(&FORGED).cast()
}

#[unsafe(no_mangle)]
pub extern "C" fn groove_grammar_name() -> *const c_char {
    c"stalegrammar".as_ptr()
}

/// `rs`, while the loader looks for this file under `py`.
///
/// The same move `flaky_language.rs` makes, and here it is what keeps the mutation probe sound:
/// disable the Tree-sitter range check and the run stops at the extension mismatch, which is
/// upstream of the tags query. Declaring `py` would instead send [`FORGED`] on to
/// `TagsConfiguration`, and a probe that has to read a zeroed parse table proves nothing about
/// the check it removed.
#[unsafe(no_mangle)]
pub extern "C" fn groove_grammar_extensions() -> *const c_char {
    c"rs".as_ptr()
}

/// Valid, and never compiled: the loader returns before it builds anything from the grammar.
///
/// # Safety
///
/// `len` must be null or point at a writable `usize`, the same contract
/// [`groove_grammar_abi::groove_grammar_plugin`] states for the export it generates.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn groove_grammar_tags_query(len: *mut usize) -> *const u8 {
    let query: &'static str = "";
    if !len.is_null() {
        // SAFETY: the caller contracts to pass a writable `usize` or null, and null is checked.
        unsafe { *len = query.len() };
    }
    query.as_ptr()
}

#[unsafe(no_mangle)]
pub extern "C" fn groove_grammar_build_info() -> *const c_char {
    c"grooveseek test fixture; grammar stalegrammar".as_ptr()
}
