//! (feature-56) The shape a tree-sitter grammar takes when groove loads it.
//!
//! Two paths reach this crate. A grammar compiled into `groove` itself builds a
//! [`GrammarDescriptor`] directly. A grammar shipped as a separate dynamic library builds the
//! same descriptor and exports it across a C ABI, which the loader reads back (arriving with
//! the loader itself). Both end up as the same descriptor, so the chunker never learns which
//! way a grammar got there.
//!
//! The descriptor deliberately carries no code of its own: a grammar contributes a parse
//! table and a tags query, and everything groove does with them — walking scopes, collecting
//! doc comments, deciding chunk boundaries — is written once, in a language-agnostic way, on
//! groove's side. Adding a language is supplying data.
//!
//! # ABI stability
//!
//! [`ABI_VERSION`] is groove's own contract number, not tree-sitter's. It changes when the set
//! of exported symbols or their signatures change, which is why a plugin states it and the
//! loader refuses anything else. The grammar's own tree-sitter ABI is a separate check.

#![forbid(unsafe_code)]

/// Version of groove's grammar contract. A plugin declaring anything else is refused.
pub const ABI_VERSION: u32 = 1;

/// Everything groove needs to parse one language.
///
/// `extension` is the single file extension this grammar claims, without a leading dot. One
/// grammar claims one extension: the registry keys parsers by extension and treats the
/// enabled id as that key, so a second extension would need a second identity to be enabled
/// or disabled by. The ABI reserves a separator for a future multi-extension form, but this
/// version refuses a declaration that uses it.
pub struct GrammarDescriptor {
    /// Lowercase language name, as it appears in the `lang:` tag on every chunk (`"rust"`).
    pub name: &'static str,
    /// Lowercase file extension without a dot (`"rs"`).
    pub extension: &'static str,
    /// The generated parse table.
    pub language: tree_sitter_language::LanguageFn,
    /// The grammar's `tags.scm`, which is what turns a parse tree into definitions.
    pub tags_query: &'static str,
}

/// Separator reserved for a future grammar that claims more than one extension.
///
/// Declared here rather than in the loader so that both sides of the ABI agree on it before
/// anything is built against it.
pub const EXTENSION_SEPARATOR: char = ';';

/// The exported symbol names, NUL-terminated for `dlsym`.
///
/// Here rather than in the loader for the same reason as [`EXTENSION_SEPARATOR`]: a plugin
/// generated by [`groove_grammar_plugin!`] and the loader that opens it are compiled from
/// different crates at different times, and a name that agreed only by convention would drift.
/// The loader looks each of these up in the order they are listed. The order it then *checks*
/// what they returned in is a separate question and not this one — the extension is settled
/// before the name, and [`symbols::BUILD_INFO`] is never checked at all — so that order is
/// documented in the loader, where it is decided, rather than here.
pub mod symbols {
    /// `uint32_t groove_grammar_abi_version(void)` — must return [`super::ABI_VERSION`].
    pub const ABI_VERSION: &[u8] = b"groove_grammar_abi_version\0";
    /// `const void *groove_grammar_language(void)` — a `const TSLanguage *`.
    pub const LANGUAGE: &[u8] = b"groove_grammar_language\0";
    /// `const char *groove_grammar_name(void)` — NUL-terminated ASCII.
    pub const NAME: &[u8] = b"groove_grammar_name\0";
    /// `const char *groove_grammar_extensions(void)` — NUL-terminated; see
    /// [`super::EXTENSION_SEPARATOR`].
    pub const EXTENSIONS: &[u8] = b"groove_grammar_extensions\0";
    /// `const uint8_t *groove_grammar_tags_query(size_t *len)` — length out-parameter rather
    /// than a NUL terminator, because a tags query is data and may legitimately embed one.
    pub const TAGS_QUERY: &[u8] = b"groove_grammar_tags_query\0";
    /// `const char *groove_grammar_build_info(void)` — diagnostic only, logged on load.
    pub const BUILD_INFO: &[u8] = b"groove_grammar_build_info\0";
}

/// Export a grammar across the C ABI this crate defines.
///
/// A plugin crate is `crate-type = ["cdylib"]`, depends on a `tree-sitter-<lang>` crate and on
/// this one, and invokes this macro once. Everything else groove needs — walking scopes,
/// collecting doc comments, deciding chunk boundaries — is on groove's side, which is what
/// keeps adding a language to supplying data.
///
/// `name` and `extension` must be string **literals**: the exported functions hand back
/// pointers to NUL-terminated static data, which is built here with `concat!`.
///
/// The expansion defines `#[unsafe(no_mangle)] pub extern "C"` functions and dereferences the
/// caller's out-pointer, so the invoking crate must permit unsafe code. That is inherent to
/// being a dynamic library with a C entry point, not a choice this macro makes — this crate
/// itself stays `#![forbid(unsafe_code)]`.
///
/// ```ignore
/// groove_grammar_abi::groove_grammar_plugin! {
///     name = "python",
///     extension = "py",
///     language = tree_sitter_python::LANGUAGE,
///     tags_query = tree_sitter_python::TAGS_QUERY,
/// }
/// ```
#[macro_export]
macro_rules! groove_grammar_plugin {
    (
        name = $name:literal,
        extension = $extension:literal,
        language = $language:expr,
        tags_query = $tags_query:expr $(,)?
    ) => {
        /// groove's grammar contract number this plugin was built against.
        #[unsafe(no_mangle)]
        pub extern "C" fn groove_grammar_abi_version() -> u32 {
            $crate::ABI_VERSION
        }

        /// The raw `TSLanguage *` the Tree-sitter CLI generated for this grammar.
        ///
        /// Handing over the raw pointer rather than the `LanguageFn` wrapper is what lets the
        /// plugin depend on `tree-sitter-language` alone: the tree-sitter runtime lives in
        /// groove, and only one copy of it ever exists.
        #[unsafe(no_mangle)]
        pub extern "C" fn groove_grammar_language() -> *const () {
            // SAFETY: `into_raw` returns the `extern "C"` function the Tree-sitter CLI
            // generated, whose only job is to return a pointer to a static parse table.
            unsafe { ($language.into_raw())() }
        }

        #[unsafe(no_mangle)]
        pub extern "C" fn groove_grammar_name() -> *const ::core::ffi::c_char {
            concat!($name, "\0").as_ptr() as *const ::core::ffi::c_char
        }

        #[unsafe(no_mangle)]
        pub extern "C" fn groove_grammar_extensions() -> *const ::core::ffi::c_char {
            concat!($extension, "\0").as_ptr() as *const ::core::ffi::c_char
        }

        /// Pointer and length of the tags query. Not NUL-terminated: the query is data.
        ///
        /// # Safety
        ///
        /// `len` must be null or point at a writable `usize`. Declared `unsafe` because it
        /// writes through that pointer; the exported symbol and calling convention are
        /// unchanged, since `unsafe` on an `extern "C" fn` constrains Rust callers only.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn groove_grammar_tags_query(len: *mut usize) -> *const u8 {
            let query: &'static str = $tags_query;
            if !len.is_null() {
                // SAFETY: the caller contracts to pass a writable `usize` or null, and null
                // is checked above.
                unsafe { *len = query.len() };
            }
            query.as_ptr()
        }

        /// What built this, for the line groove logs when the plugin loads.
        ///
        /// Carries no ABI version: `groove_grammar_abi_version` already reports it, and a
        /// second copy is a second thing to keep in step.
        #[unsafe(no_mangle)]
        pub extern "C" fn groove_grammar_build_info() -> *const ::core::ffi::c_char {
            concat!(
                env!("CARGO_PKG_NAME"),
                " ",
                env!("CARGO_PKG_VERSION"),
                "; grammar ",
                $name,
                "\0"
            )
            .as_ptr() as *const ::core::ffi::c_char
        }
    };
}

/// Whether a declared extension is one groove will accept.
///
/// Rejects the empty string, a leading dot, anything outside lowercase ASCII alphanumerics,
/// anything unreasonably long, and — for this ABI version — a multi-extension declaration.
/// A plugin is arbitrary native code, so the strings it hands back are checked like any
/// other untrusted input before they reach a filesystem walk.
///
/// A free function rather than only a method on [`GrammarDescriptor`]:
/// [`GrammarDescriptor::extension`] is `&'static str`, which a compiled-in grammar has and a
/// string just copied out of a freshly opened library does not. The rule is one rule, so it is
/// written once and takes whatever lifetime the caller has.
pub fn extension_is_valid(extension: &str) -> bool {
    !extension.is_empty()
        && extension.len() <= 64
        && !extension.contains(EXTENSION_SEPARATOR)
        && extension
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit())
}

/// Whether a declared language name is one groove will accept.
///
/// The name is not decoration: it becomes the `lang:` tag on every chunk the grammar produces,
/// so a filter like `lang:python` is written against it. A plugin that hands back an empty
/// string, or one in a case nobody would guess, loads successfully and then makes those filters
/// match nothing — a failure with no error attached to it. Checking here turns that into a
/// refusal the user can read.
///
/// Slightly wider than [`extension_is_valid`], because a language name is prose where an
/// extension is a file suffix: `-` and `_` are allowed, so `c-sharp` and `objective_c` are
/// spellable.
pub fn name_is_valid(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 64
        && name
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-' || b == b'_')
}

impl GrammarDescriptor {
    /// Whether this descriptor's declared extension is one groove will accept.
    ///
    /// See [`extension_is_valid`], which holds the rule.
    pub fn extension_is_valid(&self) -> bool {
        extension_is_valid(self.extension)
    }

    /// Whether this descriptor's declared language name is one groove will accept.
    ///
    /// See [`name_is_valid`], which holds the rule.
    pub fn name_is_valid(&self) -> bool {
        name_is_valid(self.name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The compiled-in path is held to the same contract the loader enforces on a plugin.
    ///
    /// Without this, the rules could tighten on one side only, and the grammar nobody has to
    /// place would be the one that stopped satisfying them.
    #[test]
    fn the_rules_a_plugin_must_satisfy_accept_an_ordinary_descriptor() {
        assert!(extension_is_valid("py"));
        assert!(extension_is_valid("rs"));
        assert!(name_is_valid("python"));
        assert!(name_is_valid("c-sharp"));
        assert!(name_is_valid("objective_c"));
    }

    #[test]
    fn an_extension_groove_cannot_key_a_parser_by_is_refused() {
        assert!(!extension_is_valid(""), "empty");
        assert!(!extension_is_valid(".py"), "leading dot");
        assert!(!extension_is_valid("PY"), "uppercase");
        assert!(!extension_is_valid("py;pyi"), "the reserved separator");
        assert!(!extension_is_valid(&"p".repeat(65)), "unreasonably long");
    }

    /// The name reaches search filters as `lang:<name>`, so the same shapes are refused —
    /// plus the ones that would still key a parser but read as nothing to a user.
    #[test]
    fn a_language_name_no_filter_could_match_is_refused() {
        assert!(!name_is_valid(""), "empty");
        assert!(!name_is_valid("Python"), "uppercase");
        assert!(!name_is_valid("py thon"), "whitespace");
        assert!(!name_is_valid("py:thon"), "the tag separator itself");
        assert!(!name_is_valid(&"p".repeat(65)), "unreasonably long");
    }
}
